# This file was generated by GoReleaser. DO NOT EDIT.
cask "emoji-tools" do
  version "0.9.0"

  on_macos do
    on_arm do
      sha256 "20af08ebae3124551371a95a3c2bba6a50187a511a565be4c5a0959ee042ad0c"
      url "https://github.com/jordan-simonovski/emoji-tools/releases/download/v#{version}/emoji-tools_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "e03df820ede6544b779017e32de194de6c3731257bdc3cf3aa792a61e747dc85"
      url "https://github.com/jordan-simonovski/emoji-tools/releases/download/v#{version}/emoji-tools_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "0667e497718ef7ed18d0425bc10f4fc2f0eeb07b5f66a6aa1f4cd5a27d6d6f85"
      url "https://github.com/jordan-simonovski/emoji-tools/releases/download/v#{version}/emoji-tools_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "a2df928d8050adb22cfd42ca66807b1e82a9e0f45c514dffca6b6eb2ed52d1ef"
      url "https://github.com/jordan-simonovski/emoji-tools/releases/download/v#{version}/emoji-tools_linux_amd64.tar.gz"
    end
  end

  name "emoji-tools"
  desc "Turn logos into Slack emojis: grids, scrolls, intensify, yells-at, uwu"
  homepage "https://github.com/jordan-simonovski/emoji-tools"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "emoji-tools"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/emoji-tools"]
    end
  end

  # No zap stanza required
end
