# This file was generated by GoReleaser. DO NOT EDIT.
cask "emoji-tools" do
  postflight_steps do
    on_macos do
      run "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "{{staged_path}}/emoji-tools"], must_succeed: false
    end
  end

  version "0.10.0"

  on_macos do
    on_arm do
      sha256 "2070edbf0ce2317482e60b051526ac0c4d8c0f77d1a67ef7bac7a5b85748364a"
      url "https://github.com/jordan-simonovski/emoji-tools/releases/download/v#{version}/emoji-tools_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "53ef2db702544f9877ccca2eba86375d7016d2791ca1b8091917f80d4b2568e6"
      url "https://github.com/jordan-simonovski/emoji-tools/releases/download/v#{version}/emoji-tools_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "6db4774762e27a16c8829e9a09e0197d9ad2604198d351226f11e5d41ddff065"
      url "https://github.com/jordan-simonovski/emoji-tools/releases/download/v#{version}/emoji-tools_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "3974633a701fad8ab680d1a4ac846229c0a5f5b7ec50e3dec01aca0ceebff829"
      url "https://github.com/jordan-simonovski/emoji-tools/releases/download/v#{version}/emoji-tools_linux_amd64.tar.gz"
    end
  end

  name "emoji-tools"
  desc "Turn logos into Slack emojis: grids, scrolls, intensify, yells-at, uwu"
  homepage "https://github.com/jordan-simonovski/emoji-tools"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "emoji-tools"

  # No zap stanza required
end
