# This file was generated by GoReleaser. DO NOT EDIT.
cask "emoji-tools" do
  version "0.4.0"

  on_macos do
    on_intel do
      sha256 "506007dd21cb862130699cddf606d6f33ec585708cd1aefb23993e91a387e9f1"
      url "https://github.com/jordan-simonovski/emoji-tools/releases/download/v#{version}/emoji-tools_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "e824c148bfe316f95d12a7aa57f9695521e0ff66e3413fe7867959e3824dc018"
      url "https://github.com/jordan-simonovski/emoji-tools/releases/download/v#{version}/emoji-tools_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "cc4281cf541e800d217e9d3798dcaf15b63bb09fa17a56b32320a4c556b9a28a"
      url "https://github.com/jordan-simonovski/emoji-tools/releases/download/v#{version}/emoji-tools_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "1d51072528a4b47222800485e239def8af5ab6c80aca5352c67297172579722f"
      url "https://github.com/jordan-simonovski/emoji-tools/releases/download/v#{version}/emoji-tools_linux_arm64.tar.gz"
    end
  end

  name "emoji-tools"
  desc "Turn logos into Slack emojis: grids, scrolls, intensify, yells-at, uwu"
  homepage "https://github.com/jordan-simonovski/emoji-tools"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "emoji-tools"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/emoji-tools"]
    end
  end

  # No zap stanza required

end
